// Generated by Wrangler on Sat Feb 01 2025 16:04:47 GMT+0100 (Midden-Europese standaardtijd)
// by running `wrangler types`

interface Env {
  NTFY_TOPIC: string;
  NTFY_URL: string;
  NTFY_BEARER: string;
}
