// Generated by Wrangler by running `wrangler types`

interface Env {
  NVIDIA_FE_KV: KVNamespace;
  NTFY_TOPIC: string;
  NTFY_URL: string;
  NTFY_BEARER: string;
  NTFY_TOPIC_5080: string;
  NTFY_TOPIC_5090: string;
}
